server:
  port: 8080

spring:
  application:
    name: booking
  datasource:
    url: jdbc:h2:mem:booking
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /console/